permalink: /posts/:title
markdown: kramdown

karmdown:
  math_engine: mathjax

plugins:
  - jekyll-sitemap

show_drafts: false

name: Peter Raum
url: https://rauminoodles.github.io
description: Rauminoodles
twitter: rauminoodles
github: rauminoodles
