permalink: /posts/:title
markdown: kramdown

karmdown:
  math_engine: katex

plugins:
  - jekyll-sitemap

name: Peter Raum
url: https://rauminoodles.github.io
description: Rauminoodles
twitter: rauminoodles
github: rauminoodles
